feature: ajout diagramme CU
LeniChabilan/SAE-CONCERT pull request #1
Opened 2023-10-23 13:13 UTC by LANDONNOMINECyril

si ce diagramme vous convient, pour l'instant, vous pouvez accepter cette PR, ce diagramme est évolutif et changera surement au cours de la SAE

2023-10-23 13:14 UTC, LiamSottier approved these changes
cette premiere version de diagramme me semble bien, je merge

2023-10-23 13:16 UTC, AntoineDebray1 approved these changes
Tous me semble bien

2023-10-23 13:25 UTC, LeniChabilan requested changes
Le diagramme est bien mais il manque l'acteur artiste qui doit remplir un formulaire

2023-10-23 13:26 UTC, LANDONNOMINECyril commented
je suis d'accord leni, je vais progresser de ce côté pour intégrer ces modifications

2023-10-24 06:39 UTC, LANDONNOMINECyril commented
j'ai effectué les changements demandé, je redemande votre avis sur ce diagramme

2023-10-24 06:42 UTC, AntoineDebray1 approved these changes
Cela me semble bien

2023-10-24 06:43 UTC, NoaJacquet approved these changes
oui c'est parfait

2023-10-24 06:43 UTC, LeniChabilan approved these changes
cela ma va

2023-10-24 06:44 UTC, LiamSottier approved these changes
le diagramme me semble bien

2023-10-24 06:44 UTC, merged